### ISSUE TITLE
Request push access for new proposed solution

### ISSUE THREAD

**Issue by jenningsdt** [biodiversity-specimen-data/specimen-data-use-case#5]
Dear @biodiversity-specimen-data/maintainers,

I have developed, and would like to contribute, a solution to the [Report metrics for collections within an institution](https://biodiversity-specimen-data.github.io/specimen-data-use-case/use-case/report-institution-metrics.html) use case. Is there any sort of review process for proposed solutions? I have already had @ekrimmel look at my solution via iDigBio Slack. I have both Rmd and rendered HTML files ready to upload, assuming you grant me push access. I am also willing to help you maintain the repository.

Thanks,

David Jennings

**Comment by ekrimmel** [comment]
Dear Mr. Jennings,

Thank you for your interest! I have added you to the maintainers team on this organization and you ought to now have the appropriate level of permissions to push your new solution into this repo.

Ever the bestest wishes,
Erica Krimmel
